### ISSUE TITLE
Mail in sent folder not syncronized with mail server

### ISSUE THREAD

**Issue by tanrak** [M66B/open-source-email#29]
Now that the problem #24 is solved, a new one is here.
If i send a mail from the app, the mail appear only in the sent folder of the app but not in the webmail respectively in any other mailclient. The sync of the sent folder only work from server to client but not from client to server. Maybe this is a problem of my mail provider?!

**Comment by M66B** [comment]
This should be fixed in the next release.

**Comment by tanrak** [comment]
This seems not fixed. The notification shows "*@*.*/Sent failed" - seen without uid
Regardless, the app gets better and better. Thanks for this.

**Comment by M66B** [comment]
Indeed, I reverted the change because other people ended up with two sent messages.

**Comment by M66B** [comment]
Can you please send me the debug info (available via the 'about' navigation menu) after you have got the mentioned notification, so I can see what is going on?

**Comment by tanrak** [comment]
Is on the way.

**Comment by tanrak** [comment]
In 0.13 the problem is present but without error message.

**Comment by M66B** [comment]
It is debatable if this is a problem with the app or with the email provider (which one?), since the email provider should store sent messages and report back sent messages to the app.

Do you use the SMTP server of the email provider or another one?

**Comment by tanrak** [comment]
It is the SMTP server of the provider (all-inkl.com). I can contact the support. Maybe you have a little technical background for me about the problem of the provider?

**Comment by M66B** [comment]
I don't think contacting support will help and there are likely other providers with the same issue, so I am going to try to workaround this.

Do you use both the IMAP and SMTP server of this provider?

**Comment by tanrak** [comment]
Yes. I use both from this provider. If it helps, i can make a temporary mail account for you.

**Comment by M66B** [comment]
Please make a temporary account, you can use this contact form to send me the details:
https://contact.faircode.eu/?product=other

**Comment by M66B** [comment]
@tanrak thanks for providing a test account!

**Comment by M66B** [comment]
From version 0.15 you'll need to enable the advanced option *Store sent messages*.

https://github.com/M66B/open-source-email/releases/tag/0.15

**Comment by M66B** [comment]
Yes, the setting should be per account, which is why I will reopen this issue.

**Comment by M66B** [comment]
The settings has been moved in the latest version.
